### ISSUE TITLE
Settled-thread gate crashes on a general PR comment (Thread.path is None), dropping the whole review

### ISSUE THREAD

**Issue by sblattj** [sblattj/prxref#54]
**Observed** — On 0.12.0, reviewing a Bitbucket Server PR that has at least one general (unanchored) comment and at least one finding produces nothing: the CLI prints `review failed: 'NoneType' object has no attribute 'startswith'` and exits 0. No inline comments and no summary are posted.

**Mechanism** — `apply_settled_thread_suppression` (new in 0.12.0, the inbox issue 06 fix) normalises each thread's path with `_normalised_path(t.path)`, which calls `str.startswith`. `Thread.path` is declared `str | None` and is `None` for any general PR comment, which is near-universal on Bitbucket Server. The pass chain in `orchestrate_review` is not wrapped, so the exception escapes to the CLI's catch-all.

Reproduction: one `Finding` plus one `Thread(path=None, body_snippet=..., author=...)` through `apply_settled_thread_suppression` raises `AttributeError`.

**Expected** — A path-less thread cannot be "same path" as any finding, so it should simply be skipped by this gate; the review must post as before. Reported by the 2026-09-04 audit client against PR 48 after upgrading to 0.12.0.

🤖 Filed from the ferry audit log — Fable 5.1 via Claude Code (session 68f0a704)

**Comment by sblattj** [comment]
Fixed in 0.12.1 by #55; independently verified by the original reporter on syf-mcp (PRs with general comments now review cleanly). Closing as verified.
